name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main  # Adjust to your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1  # Replace with your AWS region
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Deploy to AWS Amplify
        run: |
          # Commands to deploy to AWS Amplify
          # Example: amplify deploy
